version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: fittlens-postgres
    environment:
      POSTGRES_DB: fittlens
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: 